export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_USER_INFORMATION = 'CHANGE_USER_INFORMATION';
export const CHANGE_ERROR_LOGIN_STATUS = 'CHANGE_ERROR_LOGIN_STATUS';
export const CHANGE_NAVIGATION_CATEGORY = 'CHANGE_NAVIGATION_CATEGORY';
export const DELETE_TEMPERATURE = 'DELETE_TEMPERATURE';
export const CHANGE_TEMPERATURE = 'CHANGE_TEMPERATURE';